receivers:
  filelog:
    include: [./flog/*.log]
    poll_interval: 200ms
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: '0.0.0.0:4317'
      http:
        cors:
          allowed_origins: ['*']
          allowed_headers: ['*']
        include_metadata: true
        endpoint: '0.0.0.0:4318'
processors:
  resourcedetection:
    detectors:
      - env
      - system
      - docker
    timeout: 5s
    override: false
  batch:
  memory_limiter:
    limit_mib: 12800
    spike_limit_mib: 4000
    check_interval: 5s
exporters:
  clickhouse:
    async_insert: false
    create_schema: false
    compress: lz4
    endpoint: tcp://${env:CLICKHOUSE_SERVER_ENDPOINT}?dial_timeout=10s
    database: default
    ttl: 72h
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200
  otlphttp/loki:
    endpoint: http://gateway:3100/otlp
  elasticsearch:
    endpoint: http://elasticsearch:9200
extensions:
  health_check:
    endpoint: :13133
service:
  telemetry:
    metrics:
      address: ':8888'
    logs:
      level: info
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, clickhouse]
    logs:
      receivers: [otlp, filelog]
      processors: [memory_limiter, batch]
      exporters: [debug, clickhouse, otlphttp/loki, elasticsearch]
